#!/bin/bash

#SBATCH -p shared
#SBATCH -t 0-02:30
#SBATCH -c 4
#SBATCH --mem 23G
#SBATCH --job-name gatk_splitNcigarReads
#SBATCH -o %j.out
#SBATCH -e %j.err

cd /n/holyscratch01/macklis_lab/dtillman/ambient/working

module load Java/1.8
export PATH=`pwd`/gatk-4.2.5.0:$PATH

NAME=${1}

gatk SplitNCigarReads \
      -R Mus_musculus.GRCm39.dna.primary_assembly.fa \
      -I ${NAME}_markedDupes.Aligned.sortedByCoord.out.bam \
      -O ${NAME}_split.markedDupes.Aligned.sortedByCoord.out.bam
